import '@/styles/globals.css';

import React, { ReactNode } from 'react';

import Footer from '../components/templates/Footer/Footer';
import Header from '../components/templates/Header/Header';
import { abrilfatface, mulish, notojp } from '../styles/fonts';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

interface Props {
  children: ReactNode;
}

export default function Layout({ children }: Props) {
  return (
    <html lang='ja'>
      <body>
        <Header />
        <main className={`${abrilfatface.variable} ${mulish.variable} ${notojp.variable}`}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
